import FoodCard from '@/Component/Card/FoodCard';
import React from 'react';


const foodsdata = [
  {
    id: 1,
    name: "Pizza",
    slug: "pizza",
    category: "Fast Food",
    price: 12,
    rating: 4.5,
    image: "/images/pizza.jpg",
    description: "Delicious cheesy pizza with fresh toppings.",
  },
  {
    id: 2,
    name: "Burger",
    slug: "burger",
    category: "Fast Food",
    price: 8,
    rating: 4.3,
    image: "/images/burger.jpg",
    description: "Juicy beef burger with crispy lettuce and cheese.",
  },
  {
    id: 3,
    name: "Pasta",
    slug: "pasta",
    category: "Italian",
    price: 10,
    rating: 4.2,
    image: "/images/pasta.jpg",
    description: "Creamy pasta with rich sauce.",
  },
  {
    id: 4,
    name: "Sushi",
    slug: "sushi",
    category: "Japanese",
    price: 15,
    rating: 4.6,
    image: "/images/sushi.jpg",
    description: "Fresh salmon sushi rolls.",
  },
  {
    id: 5,
    name: "Fried Rice",
    slug: "fried-rice",
    category: "Chinese",
    price: 9,
    rating: 4.1,
    image: "/images/fried-rice.jpg",
    description: "Classic fried rice with vegetables.",
  },
  {
    id: 6,
    name: "Biryani",
    slug: "biryani",
    category: "Asian",
    price: 14,
    rating: 4.7,
    image: "/images/biryani.jpg",
    description: "Spicy and flavorful chicken biryani.",
  },
  {
    id: 7,
    name: "Kebab",
    slug: "kebab",
    category: "Grill",
    price: 11,
    rating: 4.4,
    image: "/images/kebab.jpg",
    description: "Grilled kebab with special spices.",
  },
  {
    id: 8,
    name: "Tacos",
    slug: "tacos",
    category: "Mexican",
    price: 7,
    rating: 4.0,
    image: "/images/tacos.jpg",
    description: "Crunchy tacos with beef filling.",
  },
  {
    id: 9,
    name: "Sandwich",
    slug: "sandwich",
    category: "Snack",
    price: 6,
    rating: 3.9,
    image: "/images/sandwich.jpg",
    description: "Fresh vegetable sandwich.",
  },
  {
    id: 10,
    name: "Salad",
    slug: "salad",
    category: "Healthy",
    price: 5,
    rating: 4.1,
    image: "/images/salad.jpg",
    description: "Healthy mixed green salad.",
  },
  {
    id: 11,
    name: "Ramen",
    slug: "ramen",
    category: "Japanese",
    price: 13,
    rating: 4.5,
    image: "/images/ramen.jpg",
    description: "Hot and spicy ramen noodles.",
  },
  {
    id: 12,
    name: "Hot Dog",
    slug: "hot-dog",
    category: "Fast Food",
    price: 6,
    rating: 4.0,
    image: "/images/hot-dog.jpg",
    description: "Classic hot dog with mustard.",
  },
  {
    id: 13,
    name: "Falafel",
    slug: "falafel",
    category: "Middle Eastern",
    price: 7,
    rating: 4.2,
    image: "/images/falafel.jpg",
    description: "Crispy falafel balls with sauce.",
  },
  {
    id: 14,
    name: "Butter Chicken",
    slug: "butter-chicken",
    category: "Indian",
    price: 12,
    rating: 4.6,
    image: "/images/butter-chicken.jpg",
    description: "Creamy butter chicken curry.",
  },
  {
    id: 15,
    name: "Fish & Chips",
    slug: "fish-chips",
    category: "British",
    price: 11,
    rating: 4.3,
    image: "/images/fish-chips.jpg",
    description: "Crispy fish with fries.",
  },
  {
    id: 16,
    name: "Pancakes",
    slug: "pancakes",
    category: "Breakfast",
    price: 7,
    rating: 4.4,
    image: "/images/pancakes.jpg",
    description: "Soft pancakes with syrup.",
  },
  {
    id: 17,
    name: "Waffles",
    slug: "waffles",
    category: "Breakfast",
    price: 8,
    rating: 4.3,
    image: "/images/waffles.jpg",
    description: "Golden waffles with honey.",
  },
  {
    id: 18,
    name: "Omelette",
    slug: "omelette",
    category: "Breakfast",
    price: 5,
    rating: 4.1,
    image: "/images/omelette.jpg",
    description: "Cheese omelette with herbs.",
  },
  {
    id: 19,
    name: "Donut",
    slug: "donut",
    category: "Dessert",
    price: 3,
    rating: 3.8,
    image: "/images/donut.jpg",
    description: "Sweet glazed donut.",
  },
  {
    id: 20,
    name: "Ice Cream",
    slug: "ice-cream",
    category: "Dessert",
    price: 4,
    rating: 4.5,
    image: "/images/ice-cream.jpg",
    description: "Vanilla ice cream scoop.",
  },
  {
    id: 21,
    name: "Chocolate Cake",
    slug: "chocolate-cake",
    category: "Dessert",
    price: 6,
    rating: 4.7,
    image: "/images/chocolate-cake.jpg",
    description: "Rich chocolate cake slice.",
  },
  {
    id: 22,
    name: "Cupcake",
    slug: "cupcake",
    category: "Dessert",
    price: 4,
    rating: 4.2,
    image: "/images/cupcake.jpg",
    description: "Soft cupcake with cream.",
  },
  {
    id: 23,
    name: "Grilled Chicken",
    slug: "grilled-chicken",
    category: "Grill",
    price: 13,
    rating: 4.6,
    image: "/images/grilled-chicken.jpg",
    description: "Juicy grilled chicken breast.",
  },
  {
    id: 24,
    name: "Shrimp Curry",
    slug: "shrimp-curry",
    category: "Seafood",
    price: 16,
    rating: 4.5,
    image: "/images/shrimp-curry.jpg",
    description: "Spicy shrimp curry.",
  },
  {
    id: 25,
    name: "Lobster",
    slug: "lobster",
    category: "Seafood",
    price: 25,
    rating: 4.8,
    image: "/images/lobster.jpg",
    description: "Premium grilled lobster.",
  },
  {
    id: 26,
    name: "Caesar Salad",
    slug: "caesar-salad",
    category: "Healthy",
    price: 9,
    rating: 4.3,
    image: "/images/caesar-salad.jpg",
    description: "Classic Caesar salad.",
  },
  {
    id: 27,
    name: "Tomato Soup",
    slug: "tomato-soup",
    category: "Soup",
    price: 6,
    rating: 4.0,
    image: "/images/tomato-soup.jpg",
    description: "Warm tomato soup.",
  },
  {
    id: 28,
    name: "Chicken Soup",
    slug: "chicken-soup",
    category: "Soup",
    price: 7,
    rating: 4.2,
    image: "/images/chicken-soup.jpg",
    description: "Healthy chicken soup.",
  },
  {
    id: 29,
    name: "Lasagna",
    slug: "lasagna",
    category: "Italian",
    price: 14,
    rating: 4.6,
    image: "/images/lasagna.jpg",
    description: "Layered cheese lasagna.",
  },
  {
    id: 30,
    name: "Mac & Cheese",
    slug: "mac-cheese",
    category: "Italian",
    price: 9,
    rating: 4.3,
    image: "/images/mac-cheese.jpg",
    description: "Creamy mac and cheese.",
  },
  {
    id: 31,
    name: "BBQ Ribs",
    slug: "bbq-ribs",
    category: "Grill",
    price: 18,
    rating: 4.7,
    image: "/images/bbq-ribs.jpg",
    description: "Smoky BBQ ribs.",
  },
  {
    id: 32,
    name: "Fried Chicken",
    slug: "fried-chicken",
    category: "Fast Food",
    price: 11,
    rating: 4.4,
    image: "/images/fried-chicken.jpg",
    description: "Crispy fried chicken.",
  },
  {
    id: 33,
    name: "Mashed Potatoes",
    slug: "mashed-potatoes",
    category: "Side Dish",
    price: 5,
    rating: 4.1,
    image: "/images/mashed-potatoes.jpg",
    description: "Creamy mashed potatoes.",
  },
  {
    id: 34,
    name: "French Fries",
    slug: "french-fries",
    category: "Fast Food",
    price: 4,
    rating: 4.2,
    image: "/images/french-fries.jpg",
    description: "Crispy french fries.",
  },
  {
    id: 35,
    name: "Cheesecake",
    slug: "cheesecake",
    category: "Dessert",
    price: 6,
    rating: 4.6,
    image: "/images/cheesecake.jpg",
    description: "Creamy cheesecake slice.",
  },
  {
    id: 36,
    name: "Milkshake",
    slug: "milkshake",
    category: "Drink",
    price: 5,
    rating: 4.3,
    image: "/images/milkshake.jpg",
    description: "Cold chocolate milkshake.",
  },
  {
    id: 37,
    name: "Smoothie",
    slug: "smoothie",
    category: "Drink",
    price: 6,
    rating: 4.4,
    image: "/images/smoothie.jpg",
    description: "Fresh fruit smoothie.",
  },
  {
    id: 38,
    name: "Coffee",
    slug: "coffee",
    category: "Drink",
    price: 3,
    rating: 4.5,
    image: "/images/coffee.jpg",
    description: "Hot black coffee.",
  },
  {
    id: 39,
    name: "Tea",
    slug: "tea",
    category: "Drink",
    price: 2,
    rating: 4.0,
    image: "/images/tea.jpg",
    description: "Classic milk tea.",
  },
  {
    id: 40,
    name: "Nachos",
    slug: "nachos",
    category: "Snack",
    price: 7,
    rating: 4.2,
    image: "/images/nachos.jpg",
    description: "Cheesy nachos platter.",
  },
  {
    id: 41,
    name: "Popcorn",
    slug: "popcorn",
    category: "Snack",
    price: 4,
    rating: 3.9,
    image: "/images/popcorn.jpg",
    description: "Salted popcorn.",
  },
  {
    id: 42,
    name: "Croissant",
    slug: "croissant",
    category: "Breakfast",
    price: 5,
    rating: 4.3,
    image: "/images/croissant.jpg",
    description: "Buttery croissant.",
  },
  {
    id: 43,
    name: "Bagel",
    slug: "bagel",
    category: "Breakfast",
    price: 4,
    rating: 4.1,
    image: "/images/bagel.jpg",
    description: "Toasted bagel with cream cheese.",
  },
  {
    id: 44,
    name: "Avocado Toast",
    slug: "avocado-toast",
    category: "Healthy",
    price: 9,
    rating: 4.6,
    image: "/images/avocado-toast.jpg",
    description: "Healthy avocado toast.",
  },
  {
    id: 45,
    name: "Dumplings",
    slug: "dumplings",
    category: "Chinese",
    price: 8,
    rating: 4.4,
    image: "/images/dumplings.jpg",
    description: "Steamed dumplings.",
  },
  {
    id: 46,
    name: "Spring Rolls",
    slug: "spring-rolls",
    category: "Chinese",
    price: 5,
    rating: 4.2,
    image: "/images/spring-rolls.jpg",
    description: "Crispy spring rolls.",
  },
  {
    id: 47,
    name: "Chow Mein",
    slug: "chow-mein",
    category: "Chinese",
    price: 10,
    rating: 4.3,
    image: "/images/chow-mein.jpg",
    description: "Classic chow mein noodles.",
  },
  {
    id: 48,
    name: "Steak",
    slug: "steak",
    category: "Grill",
    price: 20,
    rating: 4.8,
    image: "/images/steak.jpg",
    description: "Premium grilled steak.",
  },
  {
    id: 49,
    name: "Momos",
    slug: "momos",
    category: "Asian",
    price: 6,
    rating: 4.4,
    image: "/images/momos.jpg",
    description: "Steamed chicken momos.",
  },
  {
    id: 50,
    name: "Pad Thai",
    slug: "pad-thai",
    category: "Thai",
    price: 13,
    rating: 4.5,
    image: "/images/pad-thai.jpg",
    description: "Traditional Thai pad thai noodles.",
  },
];

const FoodsPages =async () => {
  await new Promise((resolve)=>setTimeout(resolve,500))
        
      
    return (
      <div>
          <h1 className="mb-4 text-center font-bold  text-2xl underline">
            totall foods {foodsdata.length}
          </h1>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {foodsdata.map((food) => (
            <FoodCard key={food.id} food={food} />
          ))}
        </div>
      </div>
    );
};

export default FoodsPages;